## Part1: Preprocessing

In [44]:
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data (2).csv

In [45]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [46]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df = application_df.drop(columns=['EIN','NAME'])
app_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [47]:
# Determine the number of unique values in each column.
app_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [48]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = app_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [49]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [50]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [51]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [52]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [53]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df = pd.get_dummies(app_df)
app_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [54]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
x = app_df.drop(columns=['IS_SUCCESSFUL']).values
y = app_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(x, y)

In [55]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
print(X_train_scaled[0])

[ 0.01394306 -0.03915041 -0.12310121 -0.03055899 -0.04500615 -0.00623504
 -0.00881785 -0.00623504 -0.17857931 -0.022486   -0.00881785 -0.00881785
  0.51726857 -0.21642557 -0.18698338 -0.19334827 -0.14601549 -0.14656994
 -0.07099329 -0.91971018 -0.04457043  0.92613763 -0.0324146  -0.00881785
 -0.01870803 -0.00623504 -1.01157374 -0.40572684 -0.03118975 -0.00881785
 -0.01649829 -0.00623504 -0.01394306 -0.01870803 -0.02789425 -0.00623504
 -0.00881785  0.         -0.01972038 -0.00881785 -0.00881785 -0.00881785
 -0.00623504 -0.05858902 -0.01763775 -0.03795283 -0.00623504 -0.04043991
 -0.00623504 -0.03180805 -0.01972038  0.         -0.00623504 -0.01247081
 -0.09245003 -0.00623504 -0.00623504  0.         -0.01870803 -0.00623504
  0.          2.14919697 -0.23909238  0.          0.          0.
 -0.02858365  0.         -0.01247081 -0.00623504 -0.00623504  0.
 -0.00623504 -0.05479325 -0.00881785 -0.05371211 -0.24342285 -0.00623504
 -0.00623504 -0.07476688 -0.01394306 -0.00623504  0.          0.
 -0.05958281 -0.00623504 -0.01972038 -0.00623504 -0.15107303 -0.04586527
 -0.02415478 -0.02991499 -0.01394306 -0.02571572 -0.01763775 -0.00623504
 -0.10696648 -0.06583112 -0.00881785  0.47127573 -0.44619096 -0.65100796
 -0.12293839 -0.03583987  0.67628977 -1.56424782 -0.14794773 -0.12583881
  3.03512584 -0.08394441 -0.17029727 -0.35242365 -0.06493162 -0.07317296
  0.02858365 -0.02858365]

## Part2: Compile, Train and Evaluate the Model

In [56]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(X_train[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=layer_1_nodes, 
                          input_dim=num_input_features, 
                          activation='relu'))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=layer_2_nodes, 
                          input_dim=layer_1_nodes, 
                          activation='relu'))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, 
                          input_dim=layer_2_nodes, 
                          activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                9360

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 11,821
Trainable params: 11,821
Non-trainable params: 0
_________________________________________________________________

In [57]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [58]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5702 - accuracy: 0.7182
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7299
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7302
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7325
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7317
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7338
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7338
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7349
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7352
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7360
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7342
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7339
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7367
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7357
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7371
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7370
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7372
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7373
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7372
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7376
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7389
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7373
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7381
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7379
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7397
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7381
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7394
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7392
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7393
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7389
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5319 - accuracy: 0.7399
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7406
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7402
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7388
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7407
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7397
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7400
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7408
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7400
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7411
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7415
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7410
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7408
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7406
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7409
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7412
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7414
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7410
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7415
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7414
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7423
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7412
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7416
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7416
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7413
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7420
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7413
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7415
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7420
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7413
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7412
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7414
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7417
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7414
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5280 - accuracy: 0.7415
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5280 - accuracy: 0.7421
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7417
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7421
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7428
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5276 - accuracy: 0.7423
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5277 - accuracy: 0.7421
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5277 - accuracy: 0.7423
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5271 - accuracy: 0.7423
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5272 - accuracy: 0.7419
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7420
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5274 - accuracy: 0.7424
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7424
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5272 - accuracy: 0.7420
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7419
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7419
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7423
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7417
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7417
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7430
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7424
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5271 - accuracy: 0.7422
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5264 - accuracy: 0.7422
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7426
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5270 - accuracy: 0.7425
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5266 - accuracy: 0.7424
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5264 - accuracy: 0.7426
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7425
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5266 - accuracy: 0.7426
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7430
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7421

In [59]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5899 - accuracy: 0.7315 - 449ms/epoch - 2ms/step
Loss: 0.5898941159248352, Accuracy: 0.7315452098846436

In [60]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/AlphabetSoupCharity.h5')
files.download('/content/AlphabetSoupCharity.h5')